/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/bigG.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BigG(props) {
  const { nodes, materials } = useGLTF('./models/bigG.gltf')
  return (
    <group position={[-3.837, 0, 0]} {...props} dispose={null}>
      <mesh  geometry={nodes.бабак.geometry} material={materials.бабак} position={[0, 0.1, 2.5]} />
    </group>
  )
}

useGLTF.preload('./models/bigG.gltf')
