/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/green.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useConfigurator } from '../contexts/Configurator';


export function Green(props) {
  const { nodes, materials } = useGLTF('./models/green.gltf')
  const {ghLenght} = useConfigurator();
  const GHLenghtScale = ghLenght/100;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.big_gh_startBAKE.geometry} material={materials['1']} 
            castShadow
            position={[0, 0, 0]}
            rotateOnWorldAxis={[2, 90]}
            scale={[1, 1, GHLenghtScale]}
            
      />
    </group>
  )
}

useGLTF.preload('./models/green.gltf')
