/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Monkey.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Monkey(props) {
  const { nodes, materials } = useGLTF('./models/Monkey.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.material} />
    </group>
  )
}

useGLTF.preload('./models/Monkey.gltf')
