/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Tep.gltf 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useConfigurator } from '../contexts/Configurator'

import * as Three from "three";

export function Tep(props) {

  // THREE.ColorManagement.enabled = true;

  const { nodes, materials } = useGLTF('./models/Tep.gltf')
  const {type} = useConfigurator();
  const {size} = useConfigurator();
  const {size2} = useConfigurator();
  const {legsColor, setLegsColor} = useConfigurator();
  const {ghLenght, setGHLenght} = useConfigurator();

  const ghLenghtScale = ghLenght / 400;

  useEffect(() => {
    materials.torc.color = new Three.Color(legsColor);
    materials.mainMat.color = new Three.Color(legsColor); 
  })


  return (
    <group {...props} dispose={null}>

            {size === 0 && (<>

            <group position={[-3.837, 2.1, 0]} >
              <mesh castShadow geometry={nodes.Cube002.geometry} material={materials.mainMat} />
              <mesh castShadow geometry={nodes.Cube002_1.geometry} material={materials.torc} />
              <mesh castShadow geometry={nodes['2х8003'].geometry} material={materials.metal} position={[0.77, -0.231, 0]} />
            </group>
            
            </>)}
            {size === 1 && (<>

            <group position={[-3.837, 2.1, 0]}>
              <mesh castShadow geometry={nodes.Cube003.geometry} material={materials.mainMat} />
              <mesh castShadow geometry={nodes.Cube003_1.geometry} material={materials.torc} />
              <mesh castShadow geometry={nodes['2х8002'].geometry} material={materials.metal} position={[1.758, -0.197, 0]} />
            </group>

            </>)}

            {size === 2 && (<>

              <group position={[-3.837, 2.1, 0]}>
                <mesh castShadow geometry={nodes.Cube004.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube004_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['2х8001'].geometry} material={materials.metal} position={[2.743, -0.104, 0]} />
              </group>

            </>)}

            {size === 3 && (<>

              <group position={[-3.837, 2.019, 0]}>
                <mesh castShadow geometry={nodes.Cube005.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube005_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['25х10004'].geometry} material={materials.metal} position={[0.763, -0.216, 0]} />
              </group>

            </>)}

            {size === 4 && (<>

              <group position={[-3.837, 2.019, 0]}>
                <mesh castShadow geometry={nodes.Cube006.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube006_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['25х10003'].geometry} material={materials.metal} position={[1.753, -0.187, 0]} />
              </group>

            </>)}

            {size === 5 && (<>

              <group position={[-3.837, 2.019, 0]}>
                <mesh castShadow geometry={nodes.Cube007.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube007_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['25х10002'].geometry} material={materials.metal} position={[2.743, -0.169, 0]} />
              </group>

            </>)}

            {size === 6 && (<>

              <group position={[-3.837, 1.979, 0]}>
                <mesh castShadow geometry={nodes.Cube008.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube008_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['25х10001'].geometry} material={materials.metal} position={[3.733, -0.129, 0]} />
              </group>

            </>)}

            {size === 7 && (<>

              <group position={[-3.837, 1.943, 0]}>
                <mesh castShadow geometry={nodes.Cube001.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube001_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['3х10004'].geometry} material={materials.metal} position={[0.821, -0.258, 0]} />
              </group>

            </>)}

            {size === 8 && (<>

              <group position={[-3.837, 1.943, 0]}>
                <mesh castShadow geometry={nodes.Cube009.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube009_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['3х10003'].geometry} material={materials.metal} position={[1.76, -0.211, 0]} />
              </group>

            </>)}

            {size === 9 && (<>

              <group position={[-3.837, 1.943, 0]}>
                <mesh castShadow geometry={nodes.Cube010.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube010_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['3х10002'].geometry} material={materials.metal} position={[2.747, -0.194, 0]} />
              </group>

            </>)}

            {size === 10 && (<>

              <group position={[-3.837, 1.945, 0]}>
                <mesh castShadow geometry={nodes.Cube011.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube011_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['3х10001'].geometry} material={materials.metal} position={[3.733, -0.186, 0]} />
              </group>

            </>)}

            {size === 11 && (<>



            </>)}

            {size === 12 && (<>

              <group position={[-3.837, 2.1, 0]} scale={[ghLenghtScale, 1, 1]}>
                <mesh castShadow geometry={nodes.Cube002.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube002_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['2х8003'].geometry} material={materials.metal} position={[0.77, -0.231, 0]} />
              </group>

            </>)}
            
            {/*  */}

            {size2 === 0 &&(
              <>
                
                <group position={[-3.837, 1.076, 0]}>
                  <mesh castShadow geometry={nodes.Cube038.geometry} material={materials.mainMat} />
                  <mesh castShadow geometry={nodes.Cube038_1.geometry} material={materials.torc} />
                  <mesh castShadow geometry={nodes['25х8007'].geometry} material={materials.wood} position={[0.769, -1.011, 0]} />
                  <mesh castShadow geometry={nodes.babka_met001.geometry} material={materials.metal} position={[0.769, 0, 0]} scale={0.402} />
                </group>

              </>
            )}

            {size2 === 1 &&(
              <>
                
                <group position={[-3.837, 1.076, 0]}>
                  <mesh castShadow geometry={nodes.Cube044.geometry} material={materials.mainMat} />
                  <mesh castShadow geometry={nodes.Cube044_1.geometry} material={materials.torc} />
                  <mesh castShadow geometry={nodes['25х8008'].geometry} material={materials.wood} position={[-0.221, -1.011, 0]} />
                  <mesh castShadow geometry={nodes.babka_met002.geometry} material={materials.metal} position={[-0.221, 0, 0]} scale={0.402} />
                </group>

              </>
            )}

            {size2 === 2 &&(
              <>
                
                <group position={[-3.837, 1.076, 0]}>
                  <mesh castShadow geometry={nodes.Cube045.geometry} material={materials.mainMat} />
                  <mesh castShadow geometry={nodes.Cube045_1.geometry} material={materials.torc} />
                  <mesh castShadow geometry={nodes['25х8009'].geometry} material={materials.wood} position={[1.762, -1.011, 0]} />
                  <mesh castShadow geometry={nodes.babka_met003.geometry} material={materials.metal} position={[1.759, 0, 0]} scale={0.402} />
                </group>

              </>
            )}

            {size2 === 3 &&(
              <>
                
              <group position={[-3.837, 1.076, 0]}>
                <mesh castShadow geometry={nodes.Cube046.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube046_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['25х8010'].geometry} material={materials.wood} position={[2.749, -1.011, 0]} />
                <mesh castShadow geometry={nodes.babka_met004.geometry} material={materials.metal} position={[2.749, 0, 0]} scale={0.402} />
              </group>

              </>
            )}

            {size2 === 4 &&(
              <>
                
              <group position={[-3.837, 0.714, 0]}>
                <mesh castShadow geometry={nodes.Cube047.geometry} material={materials.mainMat} />
                <mesh castShadow geometry={nodes.Cube047_1.geometry} material={materials.torc} />
                <mesh castShadow geometry={nodes['25х8006'].geometry} material={materials.wood} position={[3.546, 0, 0]} />
                <mesh castShadow geometry={nodes.babka_met.geometry} material={materials.metal} position={[3.546, 0, 0]} scale={0.402} />
              </group>

              </>
            )}

            {size2 === 0 &&(
              <>
                


              </>
            )}


      {/* <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-6.592, 0, 0]} /> */}
    </group>
  )
}

useGLTF.preload('./models/Tep.gltf')
